version: "3"
services:
  my-tube-server:
    build:
      dockerfile: Dockerfile
      context: ./
    container_name: my-tube-server
    ports:
      - "4000:4000"
    restart: always
    volumes:
      - .:/app
      - /app/node_modules

    env_file:
      - .env
