export const videoCategories = [
  { value: "education", label: "Education" },
  { value: "technology", label: "Technology" },
  { value: "science", label: "Science" },
  { value: "math", label: "Math" },
  { value: "coding", label: "Coding" },
  { value: "web-development", label: "Web Development" },
  { value: "mobile-development", label: "Mobile Development" },
  { value: "frontend", label: "Frontend Development" },
  { value: "backend", label: "Backend Development" },
  { value: "data-science", label: "Data Science" },
  { value: "machine-learning", label: "Machine Learning" },
  { value: "artificial-intelligence", label: "Artificial Intelligence" },
  { value: "cloud-computing", label: "Cloud Computing" },
  { value: "cybersecurity", label: "Cybersecurity" },
  { value: "devops", label: "DevOps" },
  { value: "networking", label: "Networking" },
  { value: "electronics", label: "Electronics" },
  { value: "engineering", label: "Engineering" },
  { value: "finance", label: "Finance" },
  { value: "investing", label: "Investing" },
  { value: "crypto", label: "Cryptocurrency" },
  { value: "stock-market", label: "Stock Market" },
  { value: "business", label: "Business" },
  { value: "startups", label: "Startups" },
  { value: "entrepreneurship", label: "Entrepreneurship" },
  { value: "marketing", label: "Marketing" },
  { value: "digital-marketing", label: "Digital Marketing" },
  { value: "seo", label: "SEO" },
  { value: "social-media", label: "Social Media" },
  { value: "productivity", label: "Productivity" },
  { value: "self-improvement", label: "Self Improvement" },
  { value: "psychology", label: "Psychology" },
  { value: "philosophy", label: "Philosophy" },
  { value: "motivation", label: "Motivation" },
  { value: "career", label: "Career" },
  { value: "job-interview", label: "Job Interview" },
  { value: "resume-tips", label: "Resume Tips" },
  { value: "life-coaching", label: "Life Coaching" },
  { value: "mindset", label: "Mindset" },
  { value: "meditation", label: "Meditation" },
  { value: "yoga", label: "Yoga" },
  { value: "fitness", label: "Fitness" },
  { value: "gym", label: "Gym" },
  { value: "bodybuilding", label: "Bodybuilding" },
  { value: "health", label: "Health" },
  { value: "nutrition", label: "Nutrition" },
  { value: "mental-health", label: "Mental Health" },
  { value: "parenting", label: "Parenting" },
  { value: "relationships", label: "Relationships" },
  { value: "lifestyle", label: "Lifestyle" },
  { value: "fashion", label: "Fashion" },
  { value: "beauty", label: "Beauty" },
  { value: "skincare", label: "Skincare" },
  { value: "makeup", label: "Makeup" },
  { value: "haircare", label: "Haircare" },
  { value: "cooking", label: "Cooking" },
  { value: "recipes", label: "Recipes" },
  { value: "food", label: "Food" },
  { value: "travel", label: "Travel" },
  { value: "photography", label: "Photography" },
  { value: "videography", label: "Videography" },
  { value: "cinematography", label: "Cinematography" },
  { value: "vlogs", label: "Vlogs" },
  { value: "daily-life", label: "Daily Life" },
  { value: "home-decor", label: "Home Decor" },
  { value: "real-estate", label: "Real Estate" },
  { value: "automotive", label: "Automotive" },
  { value: "cars", label: "Cars" },
  { value: "motorcycles", label: "Motorcycles" },
  { value: "sports", label: "Sports" },
  { value: "football", label: "Football" },
  { value: "cricket", label: "Cricket" },
  { value: "basketball", label: "Basketball" },
  { value: "tennis", label: "Tennis" },
  { value: "esports", label: "eSports" },
  { value: "gaming", label: "Gaming" },
  { value: "mobile-games", label: "Mobile Games" },
  { value: "pc-games", label: "PC Games" },
  { value: "console-games", label: "Console Games" },
  { value: "game-reviews", label: "Game Reviews" },
  { value: "live-streaming", label: "Live Streaming" },
  { value: "music", label: "Music" },
  { value: "music-videos", label: "Music Videos" },
  { value: "instrumental", label: "Instrumental" },
  { value: "singing", label: "Singing" },
  { value: "covers", label: "Covers" },
  { value: "remix", label: "Remix" },
  { value: "dance", label: "Dance" },
  { value: "animation", label: "Animation" },
  { value: "film-making", label: "Film Making" },
  { value: "movie-reviews", label: "Movie Reviews" },
  { value: "short-films", label: "Short Films" },
  { value: "documentary", label: "Documentary" },
  { value: "comedy", label: "Comedy" },
  { value: "funny-videos", label: "Funny Videos" },
  { value: "memes", label: "Memes" },
  { value: "challenges", label: "Challenges" },
  { value: "pranks", label: "Pranks" },
  { value: "reaction", label: "Reaction" },
  { value: "interviews", label: "Interviews" },
  { value: "news", label: "News" },
  { value: "politics", label: "Politics" },
  { value: "history", label: "History" },
  { value: "religion", label: "Religion" },
  { value: "spirituality", label: "Spirituality" },
  { value: "books", label: "Books" },
  { value: "book-reviews", label: "Book Reviews" },
  { value: "tutorials", label: "Tutorials" },
  { value: "how-to", label: "How-To" },
];
