export const videoTags = [
  { label: "Music", value: "music" },
  { label: "Gaming", value: "gaming" },
  { label: "Education", value: "education" },
  { label: "Comedy", value: "comedy" },
  { label: "Vlog", value: "vlog" },
  { label: "Technology", value: "technology" },
  { label: "Tutorial", value: "tutorial" },
  { label: "How-To", value: "how-to" },
  { label: "Entertainment", value: "entertainment" },
  { label: "Lifestyle", value: "lifestyle" },
  { label: "News", value: "news" },
  { label: "Science", value: "science" },
  { label: "Review", value: "review" },
  { label: "Reaction", value: "reaction" },
  { label: "Podcast", value: "podcast" },
  { label: "Fitness", value: "fitness" },
  { label: "Motivation", value: "motivation" },
  { label: "Self Improvement", value: "self-improvement" },
  { label: "Finance", value: "finance" },
  { label: "Crypto", value: "crypto" },
  { label: "Blockchain", value: "blockchain" },
  { label: "AI", value: "ai" },
  { label: "Machine Learning", value: "machine-learning" },
  { label: "Data Science", value: "data-science" },
  { label: "JavaScript", value: "javascript" },
  { label: "Python", value: "python" },
  { label: "React", value: "react" },
  { label: "Next.js", value: "nextjs" },
  { label: "Frontend", value: "frontend" },
  { label: "Backend", value: "backend" },
  { label: "Web Development", value: "web-development" },
  { label: "Mobile Development", value: "mobile-development" },
  { label: "App Development", value: "app-development" },
  { label: "UX Design", value: "ux-design" },
  { label: "UI Design", value: "ui-design" },
  { label: "Design", value: "design" },
  { label: "Startup", value: "startup" },
  { label: "Business", value: "business" },
  { label: "Marketing", value: "marketing" },
  { label: "Digital Marketing", value: "digital-marketing" },
  { label: "SEO", value: "seo" },
  { label: "Productivity", value: "productivity" },
  { label: "Mindset", value: "mindset" },
  { label: "Books", value: "books" },
  { label: "Interviews", value: "interviews" },
  { label: "Shorts", value: "shorts" },
  { label: "Highlights", value: "highlights" },
  { label: "Live", value: "live" },
  { label: "Travel", value: "travel" },
  { label: "Food", value: "food" },
  { label: "Cooking", value: "cooking" },
  { label: "ASMR", value: "asmr" },
  { label: "Fashion", value: "fashion" },
  { label: "Beauty", value: "beauty" },
  { label: "Hair", value: "hair" },
  { label: "Makeup", value: "makeup" },
  { label: "Nails", value: "nails" },
  { label: "Skincare", value: "skincare" },
  { label: "Fitness Tips", value: "fitness-tips" },
  { label: "Workout", value: "workout" },
  { label: "Yoga", value: "yoga" },
  { label: "Meditation", value: "meditation" },
  { label: "Motivational Speech", value: "motivational-speech" },
  { label: "Startup Ideas", value: "startup-ideas" },
  { label: "Programming", value: "programming" },
  { label: "Coding", value: "coding" },
  { label: "Bug Fixing", value: "bug-fixing" },
  { label: "Tech Reviews", value: "tech-reviews" },
  { label: "Unboxing", value: "unboxing" },
  { label: "Gadgets", value: "gadgets" },
  { label: "Camera", value: "camera" },
  { label: "Photography", value: "photography" },
  { label: "Cinematography", value: "cinematography" },
  { label: "Film", value: "film" },
  { label: "Movie Review", value: "movie-review" },
  { label: "Trailers", value: "trailers" },
  { label: "Anime", value: "anime" },
  { label: "Manga", value: "manga" },
  { label: "Streaming", value: "streaming" },
  { label: "Twitch", value: "twitch" },
  { label: "Minecraft", value: "minecraft" },
  { label: "Fortnite", value: "fortnite" },
  { label: "Roblox", value: "roblox" },
  { label: "Valorant", value: "valorant" },
  { label: "GTA", value: "gta" },
  { label: "League of Legends", value: "league-of-legends" },
  { label: "Funny", value: "funny" },
  { label: "Pranks", value: "pranks" },
  { label: "Fails", value: "fails" },
  { label: "Challenges", value: "challenges" },
  { label: "Dance", value: "dance" },
  { label: "Art", value: "art" },
  { label: "Drawing", value: "drawing" },
  { label: "Painting", value: "painting" },
  { label: "Crafts", value: "crafts" },
  { label: "Education Tech", value: "education-tech" },
  { label: "Parenting", value: "parenting" },
  { label: "Relationships", value: "relationships" },
  { label: "Motivational", value: "motivational" },
];
